framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        gc_maxlifetime: 31536000
        cookie_lifetime: 31536000
        cookie_secure: auto
        cookie_samesite: lax
        cookie_path: "@=service('request').getBaseUrl()"

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/manifest.json'
